pluginGroup = com.ronald.alpacabrackets
pluginName = Alpaca Brackets
pluginVersion = 0.1.0

platformType = IC
platformVersion = 2023.3.8

sinceBuild = 233

kotlin.stdlib.default.dependency = false
org.gradle.caching = true
org.gradle.configuration-cache = true
org.gradle.jvmargs = -Xmx2048m -Dfile.encoding=UTF-8
